#!/bin/sh -e
if [[ ! -f "./package.json" ]]; then
  echo "This script must be executed with cwd set to the app's root directory"
  exit 1
fi

echo "Deleting ./dist..."
if [[ -d './dist' ]]; then
  rm -rf dist
fi

echo "Generating ./src/version.ts"
printf '// Auto-generated by scripts/build.js\nexport const VERSION = "0.0.0-%s (%s)";\n' \
  "$(git rev-parse --short HEAD)" \
  "$(date "+%Y-%m-%d @ %H:%M:%S")" \
  >./src/version.ts

echo "Packing..."
npx pkgroll --env.NODE_ENV=production --target=es2022 --target=node22.9.0 --minify

echo "Renaming binary..."
mv dist/chip8.js dist/chip8

ls -l dist

echo ""
